### ISSUE TITLE
website da citação de template base está descontinuado.

### ISSUE THREAD

**Issue by ephiguxta** [brunomaroneze/dicbio#30]
No [final](https://github.com/ephiguxta/dicbio/blob/ecbd5b56debd9b7d674b3e6337f19f67688bd442/ProjectIntro.Rmd#L30) página principal possui uma referência ao projeto pelo qual o template do dicbio foi inspirado, acontece que o projeto citado não está ativo, o [_link_](https://dicbio.fflch.usp.br/bit.ly/VisualDictionary-BuddhistSanskrit) em questão possui a mesma _URL_ do dicbio mas com um diretório a mais, o "**bit.ly**", esse mesmo diretório não existe no projeto principal.
A minha sugestão é encontrar o código-fonte que foi utilizado anteriormente e adicionar no projeto principal, ou apenas citar outro projeto que possui um _link_ válido do "_VisualDictionary-BuddhistSanskrit_", como esse [site](https://mangalamresearch.shinyapps.io/VisualDictionaryOfBuddhistSanskrit/) do "_Mangalam Research Center for Budhists Languages_"

**Comment by brunomaroneze** [comment]
Tem razão; o erro foi por um descuido besta. Corrigi no último commit, quando fizer o pull da próxima versão, vai já estar corrigido.
